//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSS_Agua.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int ClientesID { get; set; }
        public Nullable<bool> RegistroActivo { get; set; }
        public string NombreInquilino { get; set; }
        public string NombrePropietario { get; set; }
        public Nullable<bool> CasaPropia { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public string TelefonoRecidencial { get; set; }
        public string TelefonoCelular { get; set; }
        public Nullable<System.DateTime> FechaCreación { get; set; }
        public string Comentario { get; set; }
        public string ServicioTipo { get; set; }
        public string UsuarioNombre { get; set; }
        public Nullable<bool> ServicioSuspendido { get; set; }
        public Nullable<System.DateTime> ServicioSuspendidoFecha { get; set; }
        public Nullable<decimal> MontoMensual { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> MontoPendienteMembrecia { get; set; }
    }
}
