//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSS_Agua.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplidore
    {
        public int SuplidorID { get; set; }
        public Nullable<bool> RegistroActivo { get; set; }
        public string Nombre { get; set; }
        public string TelefonoRecidencial { get; set; }
        public string TelefonoCelular { get; set; }
        public string Comentario { get; set; }
        public string UsuarioNombre { get; set; }
    }
}
