//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSS_Agua.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiarioGeneral
    {
        public int DiarioGeneralID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public string CuentaNombre { get; set; }
        public Nullable<decimal> Auxiliar { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> RegistroUsado { get; set; }
    }
}
